### ISSUE TITLE
Representing top level shape references

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#38] opened 2017-02-18 22:24 UTC
The current definition of ShExJ makes it difficult to represent shapes like the following:

```
<S> @<R>
```

without losing the label `<S>`.

Those shapes could be referenced from other declarations as in the following example:

```
<S> @<R>
<R> IRI
<T> { <p> @<S> }
```
One possibility could be to extend node constraints to contain a field `valueExpr` so the previous example could be something like:

```
{
  "type": "Schema",
  "shapes": [
    { "type": "NodeConstraint",
	  "id": "http://a.example/S"
	  "valueExpr": "http://a.example/R"
	},
    {
      "type": "NodeConstraint",
      "nodeKind": "iri",
      "id": "http://a.example/R"
    },
    {
      "type": "Shape",
      "expression": {
        "type": "TripleConstraint",
        "predicate": "http://a.example/p",
        "valueExpr": "http://a.example/S"
      },
      "id": "http://a.example/T"
    }
  ],
  "@context": "https://shexspec.github.io/context.jsonld"
}
```

Another possibility is to have an explicit labeled reference shape. Something like:

```
{
  "type": "Schema",
  "shapes": [
    {  "type": "LabeledRef",
	"id": "http://a.example/S"
	"value": "http://a.example/R"
   },
   {
     "type": "NodeConstraint",
      "nodeKind": "iri",
      "id": "http://a.example/R"
    },
    {
      "type": "Shape",
      "expression": {
        "type": "TripleConstraint",
        "predicate": "http://a.example/p",
        "valueExpr": "http://a.example/S"
      },
      "id": "http://a.example/T"
    }
  ],
  "@context": "https://shexspec.github.io/context.jsonld"
}
```

The latter approach could be better so we don't overload node constraints, although it needs a new kind of shape. At this moment, I have no strong opinion about which solution would be better.

**Comment by gkellogg** [comment] 2017-02-18 22:55
@labra Sorry, this doesn't make any sense to me. I think people need to re-think the whole notion of reference (ShapeRef or Inclusion) in ShEx, and rather look at the schema as a rooted graph of Shape Expression. In this case, having `<S> @<R>` isn't useful, and ends up being eliminated in the JSON-LD representation.

Furthermore, you can't reference a reference, as you do in <T> and this should be an error. Instead, reference the shape directly:

```
<R> IRI
<T> { <p> @<R> }
```

When I parse your shape, my processor spits out the following ShExJ:

```json
{
  "@context": "https://shexspec.github.io/context.jsonld",
  "type": "Schema",
  "shapes": [
    {
      "id": "R",
      "type": "NodeConstraint",
      "nodeKind": "iri"
    },
    {
      "id": "T",
      "type": "Shape",
      "expression": {
        "type": "TripleConstraint",
        "predicate": "p",
        "valueExpr": "R"
      }
    }
  ]
}
```

Consequentially, having a reference at the top level of a schema doesn't make sense, and may be a structural error. And referencing a reference also doesn't make sense which starts to sound like a reification issue in RDF.

**Comment by labra** [comment] 2017-02-19 05:58
Maybe you are right, as I said I have no strong opinion on how to solve this. The only concern for me is if the language allows top level references, then how we represent them.

I was trying to propose some alternatives, but maybe, a third alternative is just to forbid them, right?

So I see four alternatives right now:

1. Modify node constraints to include a field
1. Add another kind of shape to handle references
1. Dissallow top level shape references like `<S> @<R>`. In that case, should we modify the grammar to dissallow it or add a note? Are there any other similar cases that we should dissalow?
1. Ignore it leaving as it is and allow those declarations. In that case, what would be the representation? How would we roundtrip something like the following?
```
<S> @<R>
<R> IRI
<T> { <p> @<S> }
```

**Comment by gkellogg** [comment] 2017-02-19 18:54
> 1. Modify node constraints to include a field (presumably `valueExpr`

I don't really understand what this is meant to accomplish. Is this shorthand for using ShapeAnd on a NodeConstraint and some other Shape Expression?

> 2. Add another kind of shape to handle references

We have a ShapeRef, but this is really just a ShExC mechanism to identify a shape defined elsewhere. (As Inclusion is used to identify a Triple Expression defined elsewhere). The big change with JSON-LD is to not require reference structures, as it is implicit from the "ShEx data model", where it's a matter of serialization choice on where to put a specific definition, and where to just reference it. You don't see this in Turtle, as you always need to separate statements with a common subject from their references (except in the blankNodePropertyList case). In JSON-LD, node definitions can be placed everywhere, and sometimes are even duplicated, where a node reference serves as a stand-in for the node definition.

> 3. Dissallow top level shape references like `<S> @<R>`. In that case, should we modify the grammar to dissallow it or add a note? Are there any other similar cases that we should dissalow?

Currently, with @ericprud's recent changes, a Schema has `shapes: [shapeExpr+]?`, which includes `shapeRef`, which is a simple IRI or BNode. That makes `<S> @<R>` illegal, as the expectation is that the label `<S>` will be assigned to the shapeExpression `@<R>`, which is not something to which a label can be assigned, as it _is_ a label. This is perhaps a weakness in the ShExJ description, which makes it appear that a `shapeRef` is like other Shape Expressions which can have an `id`. I would consider this a syntax error, which should be called out and tested for.

> 4. Ignore it leaving as it is and allow those declarations. In that case, what would be the representation? How would we roundtrip something like the following?

Based on my response to 3, above, I don't think we can do this.

**Comment by labra** [comment] 2017-02-19 21:06
So if it is implicitly dissalowed by the abstract syntax, what would remain is to dissallow it in ShExC. 

I am not sure if it can be done by a change in the grammar or adding some note, but I think we should change something so it could be considered a syntax error.

**Comment by ericprud** [comment] 2017-02-21 21:30
I think this change to ShExC does the trick:
```
-[12]    shapeOr               ::= shapeAnd ("OR" shapeAnd)*
+[12]    shapeOr               ::= shapeAtomNoRef (("OR" shapeAnd)+ | ("AND" shapeNot)+ ("OR" shapeAnd)*)
+[00]    shapeAtomNoRef        ::= nodeConstraint shapeOrRef?
+                                | shapeDefinition
+                                | "(" shapeExpression ")"
+                                | '.'  # no constraint
```

**Comment by labra** [comment] 2017-02-22 06:56
I vote :+1 to close the issue with this change (I didn't test the grammar, but just believe in @ericprud's expertise with bnf...)

We also need to change the ShExDoc.g4 grammar to be in synch...but I will open another issue for that as it is not related to ShEx 2.0 spec...

**Comment by labra** [comment] 2017-02-22 07:04
Proposal: close 
REASON: Include the changes in the ShExC grammar proposed by Eric to dissallow top level shape references
PARTICIPANTS: @labra, @ericprud, @gkellogg 
REALATED: #39

**Comment by gkellogg** [comment] 2017-02-22 07:20
I'll update my context-free version of the EBNF and test out tomorrow.

**Comment by gkellogg** [comment] 2017-02-22 19:30
Rule `[10]` has a First/First conflict, as two clauses both can start with "NOT". As an equivalent alternative:

```
[10]    shapeExpression       ::= shapeAtomNoRef shapeOr?
                                | "NOT" (shapeAtomNoRef | shapeRef) shapeOr?
                                | shapeRef shapeOr
```

Seems to have the desired effect.

**Comment by gkellogg** [comment] 2017-02-22 20:53
I'm still picking up the pieces of my parser, but with my modified rule `[10]`, I'm good with the change.

**Comment by gkellogg** [comment] 2017-02-23 19:30
An issue has come up caused by startRefIRIREF.shex:

```
start=@<http://a.example/S1>

<http://a.example/S1> {
   <http://a.example/p1> .
}
```

Here, `start` is a shapeRef, but the grammar rule is:

    [6]     start                 ::= "START" '=' shapeExpression

IMO, it's reasonable for start to have a `shapeRef`, but `shapeExpression` does not allow this anymore. We (or I, anyway) couldn't do the following either:

    [6]     start                 ::= "START" '=' shapeExpression | shapeRef

As this creates a First/Follow conflict. We could possibly do it by changing the rule to:

    [6]     start                 ::= "START" '=' "NOT"? (shapeAtomNoRef | shapeRef) shapeOr?

**Comment by ericprud** [comment] 2017-02-24 05:47
Unfortunately, I think the `start=@<someShape>` is the most common use case. In principle, we could make start be an `inlineShapeExpression`:
``` diff
- [6]     start                 ::= "start" '=' shapeExpression
+ [6]     start                 ::= "start" '=' inlineShapeExpression
```
The `inlineShapeDefinition` doesn't allow annotations or semantic actions:
```
[30] shapeDefinition       ::= (includeSet | extraPropertySet | "CLOSED")* '{' tripleExpression? '}' annotation* semanticActions
[31] inlineShapeDefinition ::= (includeSet | extraPropertySet | "CLOSED")* '{' tripleExpression? '}'
```
This is because we wouldn't know if the annotations and semantic actions in inline shapeExpressions  `<S> { <p> { } %<l>{ blah %} }` were associated with the `shape` or the nesting `tripleExpression`. That restriction also seems sensible to apply to `start` as otherwise we have to figure out whether start actions apply before or after shape actions.

In practice, this is slightly more involved as `<S> { <p1> {  } <datatype>; <p2> . }` is unambiguous because the IRI of the next TripleConstraint is separated from the IRI of the optional (and pointless) datatype by a ';' while in `start=@<S> <S> {}`, there is no separator before the IRI of the shape declaration. One option is to duplicate the `inline*` productions with `start*` to have a [separate rule eliminating `nodeConstraint*`](https://www.w3.org/2005/01/yacker/uploads/ShEx2noRefInline?lang=perl&markup=html#prod-ShEx2noRefInline-startShapeAtom). I [mocked this up in yacker](https://www.w3.org/2005/01/yacker/uploads/ShEx2noRef), which does [accept the test case](http://tinyurl.com/hkvtpxt).

**Comment by gkellogg** [comment] 2017-02-24 18:33
Using `[6] start ::= "start" '=' inlineShapeExpression` gives me a First/Follow conflict:

    First/Follow Conflict: :IRIREF is both first and follow of _inlineShapeAtom_5

Hard to see exactly why, but my formulation avoids this conflict:

    [6]     start                 ::= "START" '=' "NOT"? (shapeAtomNoRef | shapeRef) shapeOr?

**Comment by gkellogg** [comment] 2017-02-25 01:31
looks like 1datatypeRef1 is no longer valid given change to `litNodeConstraint` and `nonLitNodeConstraint`:

```
# tripleConsraint with datatype and ref
<http://a.example/S1> {
   <http://a.example/p1> <http://a.example/dt1> @<http://a.example/S1>
}
```

Because of `dt1`, this is a `litNodeConstraint`, which is not followed by `shapeOrRef?` in `shapeAtom`, in [Eric's grammar](https://www.w3.org/2005/01/yacker/uploads/ShEx2sensible?lang=perl&markup=html).

(BTW, `[68] includeSet` doesn't seem to be exercised anywhere and is new to me.)

**Comment by gkellogg** [comment] 2017-02-27 19:47
I vote to close providing we accept my proposed change to `[6]` and keep the grammar closer to being context-free.

**Closed** 2017-03-29 17:03 UTC
Labels: bug, Voting-Needed
